### ISSUE TITLE
Last commit error

### ISSUE THREAD

**Issue by Mx74** [booya-at/freecad_glider#6]
Last commit b009a56 prevent the workbench to load:

`
cannot import name CirclePart
Traceback (most recent call last):
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/init_gui.py", line 77, in Initialize
    from . import tools
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/__init__.py", line 18, in <module>
    from . import shape_tool as shape_tool
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/shape_tool.py", line 5, in <module>
    from openglider.vector.polygon import CirclePart

Traceback (most recent call last):
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/__init__.py", line 15, in <module>
    from . import _glider as glider
<type 'exceptions.ImportError'>: cannot import name _glider
`

Back to 3f6385e

**Comment by hiaselhans** [comment]
https://github.com/booya-at/OpenGlider/commit/168229b73db6f5572cb4cc697a7a51a94848b91f
