### ISSUE TITLE
Import glider error

### ISSUE THREAD

**Issue by Mx74** [booya-at/freecad_glider#7]
Hello,

with the last commit, the import command fails:

`Running the Python command 'ImportGlider' failed:
Traceback (most recent call last):
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/__init__.py", line 212, in Activated
    self.create_glider_with_dialog()
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/__init__.py", line 195, in create_glider_with_dialog
    file_type = file_name.split('.')[1]

list index out of range`

**Comment by looooo** [comment]
only ods and json formats are supported. But ods doesn't work currently.
https://github.com/booya-at/freecad_glider/commit/6f7f21b5c0c8815facb957b9d189de0318ec9824

**Comment by Mx74** [comment]
I exported the glider, and tried to import it again. 
And got this error

**Comment by looooo** [comment]
I guess adding <file>.json will solve this issue. But if you save the freecad-file internally also the json is saved. My patch should prevent from exporting without file-format suffix.

**Comment by Mx74** [comment]
Running the Python command 'Gl2dExport' failed:
Traceback (most recent call last):
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/__init__.py", line 110, in Activated
    tools.export_2d(obj)
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/_tools.py", line 88, in export_2d
    FreeCAD.Console.PrintError('\nonly .ods and .json are supported')

global name 'FreeCAD' is not defined

**Comment by Mx74** [comment]
But indeed, importing the previously created files renamed with the suffixe .json works.

**Comment by Mx74** [comment]
Perfect
