### ISSUE TITLE
Bug with Design tools

### ISSUE THREAD

**Issue by Mx74** [booya-at/freecad_glider#8]
Since the last commit (cell offset for parachute), the design tool fails:

`Running the Python command 'CutCommand' failed:
Traceback (most recent call last):
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/__init__.py", line 52, in Activated
    Gui.Control.showDialog(self.tool(self.glider_obj))
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/__init__.py", line 330, in tool
    return design_tool.DesignTool(obj)
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/design_tool.py", line 44, in __init__
    CutLine.cuts_to_lines(self.parametric_glider)
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/design_tool.py", line 507, in cuts_to_lines
    CutLine(CutPoint(cell_nr, cut['left'], parametric_glider), 
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/design_tool.py", line 366, in __init__
    point = self.get_2D()
  File "/usr/lib/freecad-daily/Mod/freecad/freecad_glider/tools/design_tool.py", line 377, in get_2D
    return list(self.parametric_glider.shape[self.rib_nr, abs(self.rib_pos)] + [0])

unsupported operand type(s) for +: 'NoneType' and 'list'`

**Comment by looooo** [comment]
have you updated openglider too. Development happens on both libraries. For the future we will provide both libraries within the same repo (openglider). Maybe you can try uninstalling freecad glider `pip uninstall freecad-glider`, update and install openglider (eg.: `pip install https://github.com/booya-at/OpenGlider/archive/develop.zip`)

**Comment by looooo** [comment]
As it seems you haven't installed freecad-glider with pip, you have to remove it manually.

**Comment by Mx74** [comment]
Ok, got it. 
I just recreated the symbolic link in Freecad/Mod, pointing in the Openglider/Freecad and it works so far. 

Thank you for the tips. 

So from now on, we just have to update Openglider, cool.
